#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/ogloszex
#    username: root
#    password: 11mysql11
#  liquibase:
#    contexts: prod

#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://194.182.80.100:3306/ogloszex
#    username: root
#    password: 11mysql11
#  liquibase:
#    contexts: prod


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/ogloszex
    username: root
    password: 11mysql11
  liquibase:
    contexts: prod